// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw3VuzqduhmYgByEiyVF0KvLGfu-vmcec',
    appId: '1:466242668037:web:9cec6bc44534636b08be6c',
    messagingSenderId: '466242668037',
    projectId: 'stmary-pharmacy',
    authDomain: 'stmary-pharmacy.firebaseapp.com',
    storageBucket: 'stmary-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTjIdHWsuaeHFOzM6ZPHjVXdSYIrZN0R4',
    appId: '1:466242668037:android:b6904645c512de7908be6c',
    messagingSenderId: '466242668037',
    projectId: 'stmary-pharmacy',
    storageBucket: 'stmary-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgr3eSqWRqZffA3BswGV7u5JBAYidd0Mc',
    appId: '1:466242668037:ios:e8577e9cdbf739e908be6c',
    messagingSenderId: '466242668037',
    projectId: 'stmary-pharmacy',
    storageBucket: 'stmary-pharmacy.firebasestorage.app',
    iosBundleId: 'com.stmary.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgr3eSqWRqZffA3BswGV7u5JBAYidd0Mc',
    appId: '1:466242668037:ios:e8577e9cdbf739e908be6c',
    messagingSenderId: '466242668037',
    projectId: 'stmary-pharmacy',
    storageBucket: 'stmary-pharmacy.firebasestorage.app',
    iosBundleId: 'com.stmary.pharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw3VuzqduhmYgByEiyVF0KvLGfu-vmcec',
    appId: '1:466242668037:web:8740312344fd322f08be6c',
    messagingSenderId: '466242668037',
    projectId: 'stmary-pharmacy',
    authDomain: 'stmary-pharmacy.firebaseapp.com',
    storageBucket: 'stmary-pharmacy.firebasestorage.app',
  );
}
